exclude: ['*.Rmd']

lsi: false
highlighter: rouge

permalink: pretty
paginate: 6
paginate_path: "blog/page:num"

safe: true

title: Timothée Poisot
subtitle: Computational Ecologist
author: Timothée Poisot
production_url: http://timotheepoisot.fr

markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
