exclude: ['*.Rmd']

permalink: pretty
paginate: 6
paginate_path: "blog/page:num"

title: Timothée Poisot
subtitle: Computational Ecologist
author: Timothée Poisot
production_url: http://timotheepoisot.fr

kramdown:
  hard_wrap: false
  input: GFM

#markdown: redcarpet
#redcarpet:
#extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
